### ISSUE TITLE
NavigateToString() resulted in InvalidCastException 

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftEdge/WebViewFeedback#213]
Below is example program that gets System.InvalidCastException' in Microsoft.Web.WebView2.Core.dll when NavigateToString() method is called.
Fails with same exception if I use:
`Browser.Source = New System.Uri("https://microsoft.com/", System.UriKind.Absolute)`
or
`Browser.Source = New System.Uri("about:blank", System.UriKind.Absolute)`
instead of 
`Browser.NavigateToString(HTMLText)`

I added a Try..Catch around the Browser.NavigateToString() Method Call and got this result:
```
Exception thrown: 'System.InvalidCastException' in Microsoft.Web.WebView2.Core.dll
09:46:36 System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.WinForms.WebView2.NavigateToString(String htmlContent)
   at WebView2Test.WebView2Test._Lambda$__19-0() in C:\Users\MM\Documents\Visual Studio 2017\Projects\WebView2Test\WebView2Test\WebView2Test.vb:line 53
```

Tried with both .NET Framework 4.6.2 and 4.8
Microsoft.Web.WebView2 0.9.515-prerelease
Version 84.0.524.0 (Official build) canary (64-bit)
Visual Studio 2017 Version 15.9.22
Target CPU: x64 or x86 (Tried both. Fails both ways)

**WebView2Test.vb**
```
Imports Microsoft.Web.WebView2.Core
Public Class WebView2Test
    Private HTMLText As String
    Private BrowserInitializeTask As Task
    Private CountOfNavigationStartingEvents As Integer

    Sub WebView2Test_Load(sender As Object, e As EventArgs) Handles Me.Load
        CountOfNavigationStartingEvents = 0
        BrowserInitializeTask = Browser.EnsureCoreWebView2Async()
        LogFileWrite("WebView2Test_load event ended")
    End Sub

    Private Sub Browser_NavigationStarting(sender As Object, e As CoreWebView2NavigationStartingEventArgs) Handles Browser.NavigationStarting
       CountOfNavigationStartingEvents+=1
        LogFileWrite("Navigation Starting " & CStr(CountOfNavigationStartingEvents))
    End Sub

    Private Sub Browser_NavigationCompleted(sender As Object, e As CoreWebView2NavigationCompletedEventArgs) Handles Browser.NavigationCompleted
        LogFileWrite("Navigation Completed")
    End Sub
    Private Sub Browser_ContentLoading(sender As Object, e As CoreWebView2ContentLoadingEventArgs) Handles Browser.ContentLoading
        LogFileWrite("Content Loading")
    End Sub

    Private Sub Browser_SourceChanged(sender As Object, e As CoreWebView2SourceChangedEventArgs) Handles Browser.SourceChanged
        LogFileWrite("SourceChanged")
    End Sub

    Private Sub Browser_CoreWebView2Ready(sender As Object, e As EventArgs) Handles Browser.CoreWebView2Ready
        BrowserInitializeTask.ContinueWith(Sub()
                                               LogFileWrite("CoreWebView2Ready Event")
                                               HTMLText = "<!doctype html><html lang=""en""><head><title>Test</title></head><body><p>Test</p></body></html>"
                                               Browser.NavigateToString(HTMLText) ' Causes Exception: 'System.InvalidCastException' in Microsoft.Web.WebView2.Core.dll
                                               LogFileWrite("CoreWebView2Ready completed")
                                           End Sub)
    End Sub

    Private Sub LogFileWrite(ByVal s As String)
        Debug.Print(Format(Now, "HH:mm:ss") & " " & s)
    End Sub
End Class
```

**WebView2Test.designer.vb**
```
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class WebView2Test
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(WebView2Test))
        Me.Browser = New Microsoft.Web.WebView2.WinForms.WebView2()
        Me.SuspendLayout()
        '
        'Browser
        '
        Me.Browser.Location = New System.Drawing.Point(0, 0)
        Me.Browser.Name = "Browser"
        Me.Browser.Size = New System.Drawing.Size(926, 537)
        Me.Browser.Source = New System.Uri("about:blank", System.UriKind.Absolute)
        Me.Browser.TabIndex = 0
        Me.Browser.ZoomFactor = 1.0R
        '
        'WebView2Test
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(926, 537)
        Me.ControlBox = False
        Me.Controls.Add(Me.Browser)
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.MaximizeBox = False
        Me.MinimizeBox = False
        Me.Name = "WebView2Test"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "WebView2Test"
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents Browser As Microsoft.Web.WebView2.WinForms.WebView2
End Class
```

**Comment by FRsyesCD** [comment]
i have the same problem and according to Microsoft release notes about webview2 0.9.515-prerelease the minimum Microsoft Edge version is 84.0.515.0 and your using 83.0.478.37 i downloaded the beta/canary/dev channels no one of them works for me i'm searching for an answer i will reply if i find something ..

reference : https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes

**Comment by mikemeinz** [comment]
Sorry, I had two Edge programs installed. I removed the older one. I only have Version 84.0.516.1 (Official build) dev (64-bit) installed now and get same results.

**Comment by FRsyesCD** [comment]
the problem is not in how many edge versions/channels u have, read this it may be a hint i'm trying this now i'll update u if i got it to work 
https://github.com/MicrosoftDocs/edge-developer/issues/686

**Comment by FRsyesCD** [comment]
so i did the following steps to get it work just fine : 
1- download the Microsoft Edge Version 84.0.524.0 (Official build) **canary** (64-bit) and install it .
2- install the Microsoft.Web.WebView2 0.9.515-prerelease package from nuget packages on visual studio 2017 or higher (instructions in the image bellow).
3- make your application target x86 platform (instructions in the image bellow) .

Enjoy .
![32bit mode](https://user-images.githubusercontent.com/61872358/82906702-8a57b480-9f5d-11ea-8156-0d27c092d06e.PNG)
![webview2](https://user-images.githubusercontent.com/61872358/82906710-8af04b00-9f5d-11ea-9697-54d8fcf1f52d.PNG)

**Comment by mikemeinz** [comment]
Still not working for me.

Here is what I did:
1. Downloaded and installed Canary Version
2. Uninstalled the 516 dev Version
3. Uninstalled Microsoft.Web.WebView2 NuGet package
4. Set Build / Platform Target to **x86**
5. Deleted obj and bin folders
6. Installed Microsoft.Web.WebView2 NuGet package 0.9.515-prerelease
7. Selected **Rebuild** to build the exe
 
This is only Chromium-based Edge installed on my PC.
       Version 84.0.524.0 (Official build) canary (64-bit)

Error message:
```
Exception thrown: 'System.InvalidCastException' in Microsoft.Web.WebView2.Core.dll
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.WinForms.WebView2.NavigateToString(String htmlContent)
   at WebView2.WebView.<Browser_CoreWebView2Ready>b__12_0(Task t) in C:\Users\MM\Documents\Visual Studio 2017\Projects\WebView2Test\WebView2\WebView.cs:line 82
```

using System;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Web.WebView2.Core;
namespace WebView2
{
    public partial class WebView : Form
    {
        public WebView()
        {
            InitializeComponent();
            this.Load += WebView2Test_Load;
        }


        private string HTMLText;
        private Task BrowserInitializeTask;
        private int CountOfNavigationStartingEvents;

        public void WebView2Test_Load(object sender, EventArgs e)
        {
            CountOfNavigationStartingEvents = 0;
            Browser.CoreWebView2Ready += Browser_CoreWebView2Ready;
            BrowserInitializeTask=Browser.EnsureCoreWebView2Async();
            LogFileWrite("WebView2Test_load event ended");
        }

        private void Browser_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
        {
            CountOfNavigationStartingEvents += 1;
            LogFileWrite($"Navigation Starting {CountOfNavigationStartingEvents.ToString()}");
        }

        private void Browser_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            LogFileWrite("Navigation Completed");
        }

        private void Browser_ContentLoading(object sender, CoreWebView2ContentLoadingEventArgs e)
        {
            LogFileWrite("Content Loading");
        }

        private void Browser_SourceChanged(object sender, CoreWebView2SourceChangedEventArgs e)
        {
            LogFileWrite("SourceChanged");
        }

        private void Browser_CoreWebView2Ready(object sender, EventArgs e)
        {
            BrowserInitializeTask.ContinueWith((t) =>
            {
                LogFileWrite("CoreWebView2Ready Event");
                Browser.NavigationStarting += Browser_NavigationStarting;
                Browser.NavigationCompleted += Browser_NavigationCompleted;
                Browser.ContentLoading += Browser_ContentLoading;
                Browser.SourceChanged += Browser_SourceChanged;
                HTMLText = "<!doctype html><html lang=\"en\"><head><title>Test</title></head><body><p>Test</p></body></html>";
            try
            {
                //Browser.NavigateToString(HTMLText); // Causes Exception thrown: 'System.InvalidCastException' in Microsoft.Web.WebView2.Core.dll
                //Browser.Source = new System.Uri("about:blank", System.UriKind.Absolute); // Causes Exception thrown: 'System.InvalidCastException' in Microsoft.Web.WebView2.Core.dll
                Browser.Source = new Uri("https://microsoft.com/", UriKind.Absolute); // Causes Exception thrown: 'System.InvalidCastException' in Microsoft.Web.WebView2.Core.dll

            }
            catch (Exception ex)
                {
                    Debug.Print(ex.ToString());
                }
            LogFileWrite("CoreWebView2Ready completed");
            });
        }

        private void LogFileWrite(string s)
        {
            Debug.Print(DateTime.Now.ToString("HH:mm:ss") + " " + s);
        }
    }
}

**Comment by mikemeinz** [comment]
Problem solved!

It was a threading issue. 

The "Unable to cast COM object..." error message was a symptom not a cause.
I solved by using the **Invoke()** method of the WebView2 control.

Here are the working VB .NET and C# examples.

**VB .NET Example**
```
Imports Microsoft.Web.WebView2.Core
Public Class WebView2Test
    Private HTMLText As String
    Private BrowserInitializeTask As Task
    Private CountOfNavigationStartingEvents As Integer
    Delegate Sub NavigationDelegate()
    Private NavigationMethod As New NavigationDelegate(AddressOf Navigation)

    Sub WebView2Test_Load(sender As Object, e As EventArgs) Handles Me.Load
        CountOfNavigationStartingEvents = 0
        BrowserInitializeTask = Browser.EnsureCoreWebView2Async()
        LogFileWrite("WebView2Test_load event ended")
    End Sub

    Private Sub Browser_NavigationStarting(sender As Object, e As CoreWebView2NavigationStartingEventArgs) Handles Browser.NavigationStarting
        CountOfNavigationStartingEvents += 1
        LogFileWrite($"Navigation Starting {CountOfNavigationStartingEvents.ToString}")
    End Sub

    Private Sub Browser_NavigationCompleted(sender As Object, e As CoreWebView2NavigationCompletedEventArgs) Handles Browser.NavigationCompleted
        LogFileWrite("Navigation Completed")
    End Sub

    Private Sub Browser_ContentLoading(sender As Object, e As CoreWebView2ContentLoadingEventArgs) Handles Browser.ContentLoading
        LogFileWrite("Content Loading")
    End Sub

    Private Sub Browser_SourceChanged(sender As Object, e As CoreWebView2SourceChangedEventArgs) Handles Browser.SourceChanged
        LogFileWrite("SourceChanged")
    End Sub

    Private Sub Browser_CoreWebView2Ready(sender As Object, e As EventArgs) Handles Browser.CoreWebView2Ready
        BrowserInitializeTask.ContinueWith(Sub(t)
                                               LogFileWrite($"EnsureCoreWebView2Async Status={t.Status}")
                                               LogFileWrite("CoreWebView2Ready Event")
                                               HTMLText = "<!doctype html><html lang=""en""><head><title>Test</title></head><body><p>Test</p></body></html>"
                                               Try
                                                   Browser.Invoke(NavigationMethod)
                                               Catch ex As Exception
                                                   LogFileWrite(ex.ToString)
                                               End Try
                                               LogFileWrite("CoreWebView2Ready completed")
                                           End Sub)
    End Sub

    Private Sub Navigation()
        'Browser.Source = New System.Uri("https://microsoft.com/", System.UriKind.Absolute)
        'Browser.Source = New System.Uri("about:blank", System.UriKind.Absolute)
        Browser.NavigateToString(HTMLText)
    End Sub

    Private Sub LogFileWrite(ByVal s As String)
        Debug.Print(Format(Now, "HH:mm:ss") & " " & s)
    End Sub

End Class
```

**C# Example**
```
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Web.WebView2.Core;
namespace WebView2
{
    public partial class WebView : Form
    {
        public WebView()
        {
            InitializeComponent();
            this.Load += WebView2Test_Load;
        }

        private string HTMLText;
        private Task BrowserInitializeTask;
        private int CountOfNavigationStartingEvents;
        Delegate DoNavigation;

        public void WebView2Test_Load(object sender, EventArgs e)
        {
            DoNavigation = (Action)delegate { Navigation(); };
            CountOfNavigationStartingEvents = 0;
            Browser.CoreWebView2Ready += Browser_CoreWebView2Ready;
            BrowserInitializeTask = Browser.EnsureCoreWebView2Async();
            LogFileWrite("WebView2Test_load event ended");
        }

        private void Browser_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
        {
            CountOfNavigationStartingEvents += 1;
            LogFileWrite($"Navigation Starting {CountOfNavigationStartingEvents.ToString()}");
        }

        private void Browser_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            LogFileWrite("Navigation Completed");
        }

        private void Browser_ContentLoading(object sender, CoreWebView2ContentLoadingEventArgs e)
        {
            LogFileWrite("Content Loading");
        }

        private void Browser_SourceChanged(object sender, CoreWebView2SourceChangedEventArgs e)
        {
            LogFileWrite("SourceChanged");
        }

        private void Browser_CoreWebView2Ready(object sender, EventArgs e)
        {
            BrowserInitializeTask.ContinueWith((t) =>
            {
                LogFileWrite($"EnsureCoreWebView2Async Status={t.Status}");
                LogFileWrite("CoreWebView2Ready Event");
                Browser.NavigationStarting += Browser_NavigationStarting;
                Browser.NavigationCompleted += Browser_NavigationCompleted;
                Browser.ContentLoading += Browser_ContentLoading;
                Browser.SourceChanged += Browser_SourceChanged;
                HTMLText = "<!doctype html><html lang=\"en\"><head><title>Test</title></head><body><p>Test</p></body></html>";
                try
                {
                    Browser.Invoke(DoNavigation);
                }
                catch (Exception ex)
                {
                   LogFileWrite(ex.ToString());
                }
                LogFileWrite("CoreWebView2Ready completed");
            });
        }

        private void Navigation()
        {
            Browser.NavigateToString(HTMLText); 
            //Browser.Source = new System.Uri("about:blank", System.UriKind.Absolute); 
            //Browser.Source = new Uri("https://microsoft.com/", UriKind.Absolute);
        }

        private void LogFileWrite(string s)
        {
            Debug.Print(DateTime.Now.ToString("HH:mm:ss") + " " + s);
        }
    }
}

```
